In [4]:
import torch

idx = torch.tensor([0, 1, 2, 3, 4])

num_idx = max(idx) + 1

out_dim = 8

torch.manual_seed(123)

embedding = torch.nn.Embedding(num_idx, out_dim)


In [5]:
print(embedding.weight)
for i in range(num_idx):
    print(embedding.weight[i])

embedding_result = embedding(idx)

print(embedding_result)
print(embedding_result == embedding.weight[idx])

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792],
        [ 0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692],
        [-0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.9624,  0.2492, -0.4845, -2.0929, -0.8199, -0.4210, -0.9620,  1.2825],
        [-0.3430, -0.6821, -0.9887, -1.7018, -0.7498, -1.1285,  0.4135,  0.2892]],
       requires_grad=True)
tensor([ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792],
       grad_fn=<SelectBackward0>)
tensor([ 0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692],
       grad_fn=<SelectBackward0>)
tensor([-0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
       grad_fn=<SelectBackward0>)
tensor([ 0.9624,  0.2492, -0.4845, -2.0929, -0.8199, -0.4210, -0.9620,  1.2825],
       grad_fn=<SelectBackward0>)
tensor([-0.3430, -0.6821, -0.9887, -1.7018, -0.7498, -1.1285,  0.4135,  0.2892],

In [6]:
one_hot = torch.nn.functional.one_hot(idx)

print(one_hot)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])


In [10]:
torch.manual_seed(123)
linear = torch.nn.Linear(num_idx, out_dim, bias=False)

print(linear.weight)
print("Linear layer weight shape:", linear.weight.shape)


Parameter containing:
tensor([[-0.1824,  0.0148, -0.2221,  0.1687, -0.3811],
        [ 0.3278, -0.3251, -0.3556, -0.2826,  0.2025],
        [-0.1652,  0.1674, -0.3796, -0.2713, -0.1642],
        [-0.0879, -0.3412,  0.2928, -0.1055,  0.1436],
        [ 0.3162,  0.0833,  0.1223,  0.4317, -0.2017],
        [ 0.1417, -0.1990,  0.3196,  0.3572, -0.4123],
        [ 0.3818,  0.2136,  0.1949,  0.1841,  0.3718],
        [-0.0590, -0.3782, -0.1283, -0.3150,  0.0296]], requires_grad=True)
Linear layer weight shape: torch.Size([8, 5])


In [11]:
print(embedding.weight)
print("Embedding layer weight shape:", embedding.weight.shape)
print(embedding.weight.T)
print("Embedding layer.T weight shape:", embedding.weight.T.shape)
linear.weight = torch.nn.Parameter(embedding.weight.T)
print(linear.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792],
        [ 0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692],
        [-0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.9624,  0.2492, -0.4845, -2.0929, -0.8199, -0.4210, -0.9620,  1.2825],
        [-0.3430, -0.6821, -0.9887, -1.7018, -0.7498, -1.1285,  0.4135,  0.2892]],
       requires_grad=True)
Embedding layer weight shape: torch.Size([5, 8])
tensor([[ 0.3374,  0.7671, -0.0770,  0.9624, -0.3430],
        [-0.1778, -1.1925, -1.0205,  0.2492, -0.6821],
        [-0.3035,  0.6984, -0.1690, -0.4845, -0.9887],
        [-0.5880, -1.4097,  0.9178, -2.0929, -1.7018],
        [ 0.3486,  0.1794,  1.5810, -0.8199, -0.7498],
        [ 0.6603,  1.8951,  1.3010, -0.4210, -1.1285],
        [-0.2196,  0.4954,  1.2753, -0.9620,  0.4135],
        [-0.3792,  0.2692, -0.2010,  1.2825,  0.2892]],
       grad_fn=<PermuteBackward0>)
Embedding layer

In [14]:
# 打印 onehot 的形状
print(one_hot)
print("One-hot encoded shape:", one_hot.shape)
print(linear.weight)
print("linear weight shape:", linear.weight.shape)
print(linear.weight.T)
print("linear weight.T shape:", linear.weight.T.shape)
# 使用 linear 层进行计算并打印输出的形状
output = linear(one_hot.float())
print(output)
print("Output shape after linear layer:", output.shape)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])
One-hot encoded shape: torch.Size([5, 5])
Parameter containing:
tensor([[ 0.3374,  0.7671, -0.0770,  0.9624, -0.3430],
        [-0.1778, -1.1925, -1.0205,  0.2492, -0.6821],
        [-0.3035,  0.6984, -0.1690, -0.4845, -0.9887],
        [-0.5880, -1.4097,  0.9178, -2.0929, -1.7018],
        [ 0.3486,  0.1794,  1.5810, -0.8199, -0.7498],
        [ 0.6603,  1.8951,  1.3010, -0.4210, -1.1285],
        [-0.2196,  0.4954,  1.2753, -0.9620,  0.4135],
        [-0.3792,  0.2692, -0.2010,  1.2825,  0.2892]], requires_grad=True)
linear weight shape: torch.Size([8, 5])
tensor([[ 0.3374, -0.1778, -0.3035, -0.5880,  0.3486,  0.6603, -0.2196, -0.3792],
        [ 0.7671, -1.1925,  0.6984, -1.4097,  0.1794,  1.8951,  0.4954,  0.2692],
        [-0.0770, -1.0205, -0.1690,  0.9178,  1.5810,  1.3010,  1.2753, -0.2010],
        [ 0.9624,  0.2492, -0.4845, -2.0929, -0.8199, -0.4210, 

In [15]:

print(embedding(idx) == output)


tensor([[True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True]])
